### ISSUE TITLE
Error on first bmake

### ISSUE THREAD

**Issue by mdgoldberg** [benesch/homebrew-os161#1]
After following the nutshell commands at the end of the README, I get errors after the first bmake (the one after ./configure). Why is that? Output is attached.

Two other questions:
1) Do I need to be running this from $HOME in order for this to work? Ideally, I would be keeping my 161 files all in my Dropbox/Junior/CS161 folder to go with my organization, but if I need to, I can run it all from root.
2) How can I replace the nutshell instructions with a clone from my code.seas repo instead? Should I just run the git clone instead of wget'ing and tar'ing the compressed directory as is done on the first two lines of the nutshell instructions?

[bmake_output.txt](https://github.com/benesch/homebrew-os161/files/112899/bmake_output.txt)

**Comment by benesch** [comment]
You do not need to be running from `$HOME`! Just configure the `ostree` appropriately when you configure userland from the root of your OS/161 checkout.

And yep, just replace the `wget` with `git clone`.

**Comment by benesch** [comment]
You can actually just completely ignore the nutshell instructions if you've followed the quick start instructions. The quick start is the equivalent of `apt-get install os161-toolchain` on the VM, so you're ready to follow the following instructions provided in class.
